name: test_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  collection: ^1.19.1

  animations: ^2.0.11

  app_settings: ^5.1.1

  file_picker: ^10.2.0
  flutter_phoenix: ^1.1.1

  #notification
  flutter_local_notifications: ^19.3.0
  permission_handler: ^12.0.1
  # workmanager: ^0.8.0
  shared_preferences: ^2.5.3

  #lock app
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.0.0 #4.0.0 for IOS | 9.0.0 for Android
  encrypt: ^5.0.3
  pointycastle: ^3.9.1

  #image and OCR
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.15.0

  flutter_speed_dial: ^7.0.0

  #MVC State Management
  provider: ^6.1.5

  #Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Currency conversion
  http: ^1.4.0

  #Report
  fl_chart: ^1.0.0

  #Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.5
  jiffy: ^6.4.3

  dotted_border: ^3.0.1

  cupertino_icons: ^1.0.8

  flutter_gen: ^5.10.0

  google_generative_ai: ^0.4.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

  hive_generator: ^2.0.1
  build_runner: ^2.4.15

  flutter_gen_runner: ^5.4.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/appBackgroundImg.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Add this at the end of your pubspec.yaml, at the same indentation level as 'flutter' or 'dev_dependencies'
flutter_launcher_icons:
  android: "launcher_icon" # can be true, false, or a string for the file name
  ios: true
  image_path: "assets/appLogo.png" # Path to your icon image
  min_sdk_android: 21 # optional